import { useState } from 'react';
import { LanguageContext } from './LanguageContextBase';

const translations = {
  en: {
    // Sidebar
    dashboard: 'Dashboard',
    patientRegistry: 'Patient Registry',
    reports: 'Reports',
    settings: 'Settings',
    allPatients: 'All Patients',
    userManagement: 'User Management',
    facilities: 'Facilities',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    neonatalCare: 'Neonatal Care',

    // Topbar
    searchPlaceholder: 'Search patient, UHID...',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    viewAllNotifications: 'View all notifications',

    // Login
    welcomeBack: 'Welcome back',
    signInDesc: 'Sign in to access the system',
    quickDemo: 'Quick Demo Login:',
    email: 'Email Address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    securedBy: 'Secured by SANKALP v2.0 · Government Health Program',
    empoweringTitle: 'Empowering Neonatal\nCare Through\nSmart Technology',
    empoweringDesc: 'A comprehensive bedside counselling and follow-up management system for hospitals and medical institutions.',
    totalPatients: 'Total Patients',
    accuracyRate: 'Accuracy Rate',
    pendingReviews: 'Pending Reviews',

    // Admin Dashboard
    hospitalManagement: 'Hospital Management Console',
    dashboardOverview: 'Dashboard › Overview',
    totalRegistrations: 'Total Registrations',
    fromLastMonth: 'from last month',
    pendingReviewsCard: 'Pending Reviews',
    urgentAttention: '8 requires urgent attention',
    approvedRecords: 'Approved Records',
    accuracyRateCard: '98.2% Accuracy rate',
    followupDefaulters: 'Follow-up Defaulters',
    highRiskCases: 'High risk cases detected',
    monthlyFacilityEntries: 'Monthly Facility Entries',
    entriesVsApproved: 'Facility-wise monthly entries over last 6 months',
    target: 'Target',
    supervisorPerformance: 'Supervisor Performance',
    liveMonitoring: 'Live Monitoring',
    realTimeStatus: 'Real-time status of neonatal registrations',
    viewAllRegistry: 'View All Registry →',
    mothersName: "Mother's Name",
    uhid: 'UHID',
    supervisor: 'Supervisor',
    date: 'Date',
    totalEntries: 'Total Entries',
    approved: 'Approved',
    draft: 'Draft',
    submitted: 'Submitted',
    returned: 'Returned',
    closed: 'Closed',

    // Supervisor Dashboard
    goodMorning: 'Good morning',
    patientOverview: "Here's your patient overview for today.",
    registerNewPatient: 'Register New Patient',
    addNewNeonate: 'Add a new neonate to the registry',
    dailyFollowup: 'Daily Follow-up List',
    viewPendingVisits: 'View all pending visits for today',
    generateSummary: 'Generate Summary',
    exportMonthly: 'Export monthly clinical report',
    casesReturned: 'case(s) returned by admin for revision',
    reviewRemarks: 'Please review admin remarks and resubmit.',
    viewCases: 'View Cases',
    myActiveRecords: 'My Active Records',
    activeRecords: 'active records under your supervision',
    viewAll: 'View All',
    patientName: 'Patient Name',
    dobAge: 'DOB / Age',
    primaryRisk: 'Primary Risk',
    actions: 'Actions',
    daysOld: 'Days Old',
    upcomingFollowups: 'Upcoming Follow-ups',
    recordsPending: 'Records Pending',
    completedVisits: 'Completed Visits',
    targetPercent: '88% target',
    highRiskAlerts: 'High Risk Alerts',
    urgent: 'Urgent',
    reviewAvgTime: 'Review Avg Time',
    efficient: 'Efficient',

    // Patient Registry
    myPatientRecords: 'My Patient Records',
    recordsFound: 'records found',
    searchByNameUhid: 'Search by name, UHID, contact...',
    patient: 'Patient',
    dob: 'DOB',
    facility: 'Facility',
    risk: 'Risk',
    updated: 'Updated',
    noRecords: 'No records found',
    noRecordsMatch: 'No records match your search',
    filters: 'Filters',
    status: 'Status',
    all: 'all',

    // New Patient
    motherDetails: 'Mother Details',
    enterMotherInfo: "Enter the mother's personal and contact information.",
    motherFullName: 'Mother Full Name',
    fatherFullName: 'Father Full Name',
    ageYears: 'Age (Years)',
    contactNumber: 'Contact Number',
    villageArea: 'Village / Area',
    ashaWorkerName: 'ASHA Worker Name',
    ashaContact: 'ASHA Contact',
    babyDetails: 'Baby Details',
    enterBabyInfo: "Enter the neonate's clinical information.",
    gender: 'Gender',
    uhidLabel: 'UHID (Unique Health ID)',
    areaType: 'Area Type',
    birthWeight: 'Birth Weight (kg)',
    gestationalAge: 'Gestational Age (weeks)',
    breastfeedingCounselling: 'Breastfeeding Counselling',
    checkTopics: 'Check all counselling topics discussed with the mother.',
    colostrumFeeding: 'Colostrum Feeding',
    colostrumDesc: 'Discussed benefits and first milk importance',
    earlyInitiation: 'Early Initiation',
    earlyInitiationDesc: 'Breastfeeding within the first hour of birth',
    exclusiveBreastfeeding: 'Exclusive Breastfeeding',
    exclusiveDesc: 'Advice on 6 months no-other-food policy',
    correctLatching: 'Correct Latching',
    latchingDesc: 'Positioning and attachment counselling done',
    prelactealFeed: 'Prelacteal Feed Avoided',
    prelactealDesc: 'Counselled to avoid prelacteal feeds',
    additionalNotes: 'Additional Notes',
    counsellingNotes: 'Any specific counselling notes...',
    kmcTitle: 'KMC (Kangaroo Mother Care)',
    kmcDesc: 'Document KMC initiation and counselling details.',
    kmcInitiated: 'KMC Initiated',
    counsellingDone: 'Counselling Done',
    providerSupport: 'Provider Support Required',
    dateOfInitiation: 'Date of Initiation',
    durationHrsDay: 'Duration (Hrs/Day)',
    acceptanceLevel: 'Acceptance Level',
    selectLevel: 'Select Level',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    problemsEncountered: 'Problems Encountered',
    dischargeTitle: 'Discharge & Danger Signs',
    criticalModule: 'CRITICAL MODULE — Discuss all danger signs with mother',
    critical: 'CRITICAL',
    discussedDanger: 'Discussed Danger Signs',
    inabilityToFeed: 'Inability to feed',
    convulsions: 'Convulsions / Fits',
    fastBreathing: 'Fast breathing (>60bpm)',
    fever: 'Fever / Cold to touch',
    yellowingOfPalms: 'Yellowing of palms/soles',
    followupDate: 'Follow-up Date',
    emergencyContact: 'Emergency Contact Confirmed?',
    yes: 'Yes',
    no: 'No',
    dischargeAdvice: 'Discharge Advice Notes',
    dischargeInstructions: 'Enter specific instructions for the mother...',
    postDischarge: 'Post-Discharge Follow-up',
    postDischargeDesc: 'Record the follow-up visit details after discharge.',
    currentFeeding: 'Current Feeding Status',
    selectStatus: 'Select Status',
    satisfactory: 'Satisfactory',
    partial: 'Partial',
    notBreastfeeding: 'Not Breastfeeding',
    currentWeight: 'Current Weight (kg)',
    feedingPattern: 'Feeding Pattern',
    nextFollowup: 'Next Follow-up Date',
    kmcContinuedHome: 'KMC Continued at Home',
    dangerSignsFound: 'Danger Signs Found',
    referral: 'Referral',
    remarks: 'Remarks',
    saveDraft: 'Save Draft',
    saved: 'Saved!',
    submittedSuccess: 'Case Submitted Successfully!',
    submittedSuccessDesc: 'The record has been submitted for admin review.',
    patientRegistration: 'Patient Registration',
    stepOf: 'Step {step} of {total}',
    discardEntry: 'Discard Entry',
    previous: 'Previous',
    nextSection: 'Next Section',
    submitForReview: 'Submit for Review',

    // Settings
    managePreferences: 'Manage your account preferences',
    profile: 'Profile',
    security: 'Security',
    fullName: 'Full Name',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    notificationsSettings: 'Notifications',
    caseReturnedAlerts: 'Case Returned Alerts',
    followupReminders: 'Follow-up Due Reminders',
    adminRemarks: 'Admin Remarks',
    systemUpdates: 'System Updates',

    // Reports
    reportsExports: 'Reports & Exports',
    reportsDesc: 'Generate and download reports in PDF or Excel format',
    monthlyReport: 'Monthly Report',
    monthlyReportDesc: 'All registrations for a specific month',
    supervisorReport: 'Supervisor Report',
    supervisorReportDesc: 'Performance and caseload by supervisor',
    facilityReport: 'Facility Report',
    facilityReportDesc: 'Facility-wise patient statistics',
    governmentReport: 'Government Report',
    governmentReportDesc: 'Official format for health department',
    monthlySummaryPreview: 'Monthly Summary Preview',
    supervisorCaseload: 'Supervisor Caseload',
    cases: 'cases',

    // User Management
    userManagementTitle: 'User Management',
    activeSupervisors: 'active supervisors',
    addSupervisor: 'Add Supervisor',
    totalUsers: 'Total Users',
    active: 'Active',
    inactive: 'Inactive',
    totalCases: 'Total Cases',
    designation: 'Designation',
    joined: 'Joined',

    // Facility
    facilityManagement: 'Facility Management',
    facilitiesDesc: 'Manage hospital departments and units',
    activeFacilities: 'active facilities',
    addFacility: 'Add Facility',
    department: 'Department',
    head: 'Head',
    patients: 'Patients',

    // Other Supervisors Modal
    otherSupervisors: 'Other Supervisors',
    allSupervisors: 'All Supervisors',
    pending: 'Pending',
    viewAllSupervisors: 'View All Supervisors',
    close: 'Close',

    // Assessment Tool - Section A
    identification: 'Identification',
    hospitalName: 'Hospital Name',
    dateOfDelivery: 'Date of Delivery',
    dateOfAssessment: 'Date of Assessment',
    assessorName: 'Name of Assessor',
    gravida: 'Gravida',
    para: 'Para',
    sexOfBaby: 'Sex of Baby',
    deliveryType: 'Delivery Type',
    normal: 'Normal',
    assisted: 'Assisted',
    caesarean: 'Caesarean',
    male: 'Male',
    female: 'Female',
    otherGender: 'Other',

    // Assessment Tool - Section B (ANC)
    ancCounselling: 'ANC Counselling (Before Delivery)',
    ancCounsellingDesc: 'Was the mother counselled during pregnancy?',
    importanceBF: 'Importance of breastfeeding',
    bfWithin1Hour: 'Breastfeeding within 1 hour',
    exclusiveBF6Months: 'Exclusive breastfeeding for 6 months',
    skinToSkin: 'Skin-to-skin contact',
    noPrelacteal: 'No pre-lacteal feeds',
    breastAssessment: 'Breast Assessment',
    flatNipple: 'Flat nipple',
    invertedNipple: 'Inverted nipple',
    breastAbnormality: 'Breast abnormality',
    prevBFDifficulty: 'Previous breastfeeding difficulty',
    actionTaken: 'Action Taken',

    // Assessment Tool - Section C (After Birth)
    afterBirthCare: 'Immediately After Birth',
    afterBirthCareDesc: 'Labour Room details',
    timeOfBirth: 'Time of Birth',
    babyCriedImmediately: 'Baby cried immediately',
    requiredResuscitation: 'Required Resuscitation',
    driedImmediately: 'Baby dried immediately',
    delayedCordClamping: 'Delayed cord clamping',
    skinToSkinInitiated: 'Skin-to-skin contact initiated',
    durationOver1Hour: 'Duration >1 hour',
    babySeparated: 'Baby separated from mother',
    reason: 'Reason',
    timeBFStarted: 'Time breastfeeding started',
    withinOneHour: 'Within one hour?',
    ifNoWhy: 'If No, Why?',
    motherSick: 'Mother sick',
    babySick: 'Baby sick',
    staffDelay: 'Staff delay',
    familyRefusal: 'Family refusal',
    colostrumGiven: 'Colostrum Given?',
    prelactealGiven: 'Pre-lacteal Feed Given?',
    type: 'Type',
    honey: 'Honey',
    water: 'Water',
    formula: 'Formula',
    animalMilk: 'Animal milk',

    // Assessment Tool - Section D (Breastfeeding Assessment)
    bfAssessment: 'Breastfeeding Assessment',
    bfAssessmentDesc: 'Observe one complete feed',
    position: 'Position',
    correct: 'Correct',
    incorrect: 'Incorrect',
    motherComfortable: 'Mother comfortable',
    babyCloseToMother: 'Baby close to mother',
    babyFacingBreast: 'Baby facing breast',
    wholeBodySupported: 'Whole body supported',
    attachment: 'Attachment',
    mouthWideOpen: 'Mouth wide open',
    chinTouchingBreast: 'Chin touching breast',
    lowerLipOutward: 'Lower lip turned outward',
    moreAreolaAbove: 'More areola visible above',
    effectiveSuckling: 'Effective Suckling',
    slowDeepSuck: 'Slow deep suck',
    swallowingHeard: 'Swallowing heard',
    babySatisfied: 'Baby satisfied',

    // Assessment Tool - Section E (Postnatal Ward)
    postnatalWard: 'Postnatal Ward',
    bfObservedByNurse: 'Was breastfeeding observed by nurse?',
    everyFeed: 'Every feed',
    onceDaily: 'Once daily',
    never: 'Never',
    motherCounselled: 'Mother was counselled regarding',
    feedingCues: 'Feeding cues',
    demandFeeding: 'Demand feeding',
    nightFeeding: 'Night feeding',
    burping: 'Burping',
    handExpression: 'Hand expression',
    familyCounselled: 'Family was counselled?',

    // Assessment Tool - Section F (Sick Baby)
    sickBaby: 'For Sick Baby (SNCU/NBSU)',
    applicable: 'Applicable?',
    motherExpressingMilk: 'Mother started expressing milk',
    within6Hours: 'Within 6 hours',
    within12Hours: 'Within 12 hours',
    over12Hours: '>12 hours',
    feedingMethod: 'Feeding Method',
    directBF: 'Direct Breastfeeding',
    cup: 'Cup',
    spoon: 'Spoon',
    tube: 'Tube',
    expressedMilk: 'Expressed Breast Milk',
    counselledDaily: 'Mother counselled daily?',

    // Assessment Tool - Section G (Daily Monitoring)
    dailyMonitoring: 'Daily Monitoring',
    bfObserved: 'Breastfeeding observed',
    goodAttachment: 'Good attachment',
    feeding8to12: 'Baby feeding 8–12 times',
    urinationAdequate: 'Urination adequate',
    stoolPassed: 'Stool passed',
    weightMonitored: 'Weight monitored',

    // Assessment Tool - Section H (Breastfeeding Problems)
    bfProblems: 'Breastfeeding Problems',
    poorAttachment: 'Poor attachment',
    breastEngorgement: 'Breast engorgement',
    crackedNipple: 'Cracked nipple',
    inadequateMilk: 'Inadequate milk',
    babySleepy: 'Baby sleepy',
    managementGiven: 'Management Given',

    // Assessment Tool - Section I (Before Discharge)
    beforeDischarge: 'Before Discharge',
    exclusivelyBF: 'Baby exclusively breastfeeding?',
    motherConfident: 'Mother confident?',
    exclusiveBFCounselling: 'Exclusive breastfeeding',
    dangerSignsCounselling: 'Danger signs',
    maternalNutrition: 'Maternal nutrition',
    homeVisitCounselling: 'Home visit',
    immunization: 'Immunization',
    followupCounselling: 'Follow-up',

    // Assessment Tool - Section J (Post-discharge Plan)
    postDischargePlan: 'Post-discharge Plan',
    ashaInformed: 'ASHA informed?',
    hbncVisitPlanned: 'HBNC Visit Planned',
    day1: 'Day 1',
    day3: 'Day 3',
    day7: 'Day 7',
    day14: 'Day 14',
    day21: 'Day 21',
    day28: 'Day 28',

    // PatientDetailAdmin bilingual fixes
    admissionLevel: 'Admission Level',
    permanentlyLocked: 'Permanently Locked',
    notYetFilled: 'Not yet filled',
    reviewSubmitted: 'Review Submitted!',
    caseStatusUpdated: 'Case status updated successfully.',
    thisCaseLocked: 'This case is permanently locked and cannot be modified.',
    caseTimeline: 'Case Timeline',
    adminReviewAction: 'Admin Review Action',
    submitReview: 'Submit Review',
    addReviewNotes: 'Add review notes or return reason...',
    systemActivityLog: 'System Activity Log',
    recentEvents: 'recent events',
    performedByLabel: 'By:',
    created: 'Created',
    motherName: 'Mother Name',
    fatherName: 'Father Name',
    age: 'Age',
    contact: 'Contact',
    village: 'Village',
    ashaWorker: 'ASHA Worker',
    area: 'Area',
    weeks: 'weeks',
    years: 'years',
    kg: 'kg',
    done: 'Done',
    notDone: 'Not done',

    // Misc
    loading: 'Loading...',
    baby: 'Baby of',
    of: 'of',
    babyOfName: 'Baby of {name}',

    // Mock Dashboard Follow-ups
    dateToday: 'Today, Oct 16',
    dateTomorrow: 'Tomorrow, Oct 17',
    babyOfAnanya: 'Baby of Ananya',
    babyOfPriya: 'Baby of Priya',
    babyOfDeepa: 'Baby of Deepa',
    followupDay14: 'Follow-up: Day 14 Visit',
    followupDay7: 'Follow-up: Day 7 Visit',
    routineWeightCheck: 'Routine Weight Check',
    chcZone4: 'Community Health Center – Zone 4',
    homeVisitGreenPark: 'Home Visit – Green Park Apts',
    sncuOpd: 'SNCU OPD',

    // Mock Names
    Meera: 'Meera',
    Rekha: 'Rekha',
    Sunita: 'Sunita',
    Meena: 'Meena',
    Priya: 'Priya',
    Sarah: 'Sarah',
  },
  hi: {
    // Sidebar
    dashboard: 'डैशबोर्ड',
    patientRegistry: 'मरीज़ रजिस्ट्री',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    allPatients: 'सभी मरीज़',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    facilities: 'सुविधाएं',
    adminPanel: 'एडमिन पैनल',
    logout: 'लॉगआउट',
    neonatalCare: 'नवजात देखभाल',

    // Topbar
    searchPlaceholder: 'मरीज़, UHID खोजें...',
    notifications: 'सूचनाएं',
    markAllRead: 'सभी पढ़ें चिन्हित करें',
    viewAllNotifications: 'सभी सूचनाएं देखें',

    // Login
    welcomeBack: 'वापसी पर स्वागत',
    signInDesc: 'सिस्टम तक पहुंचने के लिए साइन इन करें',
    quickDemo: 'त्वरित डेमो लॉगिन:',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signingIn: 'साइन इन हो रहा है...',
    signIn: 'साइन इन',
    securedBy: 'SANKALP v2.0 द्वारा सुरक्षित · सरकारी स्वास्थ्य कार्यक्रम',
    empoweringTitle: 'स्मार्ट तकनीक के माध्यम से\nनवजात देखभाल को\nसशक्त बनाना',
    empoweringDesc: 'अस्पतालों और चिकित्सा संस्थानों के लिए एक व्यापक बेडसाइड काउंसेलिंग और फॉलो-अप प्रबंधन प्रणाली।',
    totalPatients: 'कुल मरीज़',
    accuracyRate: 'सटीकता दर',
    pendingReviews: 'लंबित समीक्षा',

    // Admin Dashboard
    hospitalManagement: 'अस्पताल प्रबंधन कंसोल',
    dashboardOverview: 'डैशबोर्ड › अवलोकन',
    totalRegistrations: 'कुल पंजीकरण',
    fromLastMonth: 'पिछले महीने से',
    pendingReviewsCard: 'लंबित समीक्षा',
    urgentAttention: '8 को तत्काल ध्यान देने की आवश्यकता',
    approvedRecords: 'अनुमोदित रिकॉर्ड',
    accuracyRateCard: '98.2% सटीकता दर',
    followupDefaulters: 'फॉलो-अप डिफ़ॉल्टर',
    highRiskCases: 'उच्च जोखिम मामले पाए गए',
    monthlyFacilityEntries: 'मासिक सुविधा प्रविष्टियां',
    entriesVsApproved: 'पिछले 6 महीनों में सुविधा-वार मासिक प्रविष्टियां',
    target: 'लक्ष्य',
    supervisorPerformance: 'पर्यवेक्षक प्रदर्शन',
    liveMonitoring: 'लाइव मॉनिटरिंग',
    realTimeStatus: 'नवजात पंजीकरण की वास्तविक समय स्थिति',
    viewAllRegistry: 'सभी रजिस्ट्री देखें →',
    mothersName: 'माता का नाम',
    uhid: 'UHID',
    supervisor: 'पर्यवेक्षक',
    date: 'तारीख',
    totalEntries: 'कुल प्रविष्टियां',
    approved: 'अनुमोदित',
    draft: 'ड्राफ्ट',
    submitted: 'प्रस्तुत',
    returned: 'लौटाया',
    closed: 'बंद',

    // Supervisor Dashboard
    goodMorning: 'शुभ प्रभात',
    patientOverview: 'आज आपके मरीज़ों का अवलोकन।',
    registerNewPatient: 'नया मरीज़ पंजीकृत करें',
    addNewNeonate: 'रजिस्ट्री में एक नवजात शिशु जोड़ें',
    dailyFollowup: 'दैनिक फॉलो-अप सूची',
    viewPendingVisits: 'आज की सभी लंबित यात्राएं देखें',
    generateSummary: 'सारांश बनाएं',
    exportMonthly: 'मासिक क्लिनिकल रिपोर्ट निर्यात करें',
    casesReturned: 'मामले संशोधन के लिए एडमिन द्वारा लौटाए गए',
    reviewRemarks: 'कृपया एडमिन टिप्पणियां समीक्षा करें और फिर से प्रस्तुत करें।',
    viewCases: 'मामले देखें',
    myActiveRecords: 'मेरे सक्रिय रिकॉर्ड',
    activeRecords: 'आपकी देखरेख में सक्रिय रिकॉर्ड',
    viewAll: 'सभी देखें',
    patientName: 'मरीज़ का नाम',
    dobAge: 'जन्म तिथि / आयु',
    primaryRisk: 'प्राथमिक जोखिम',
    actions: 'कार्यवाही',
    daysOld: 'दिन पुराना',
    upcomingFollowups: 'आगामी फॉलो-अप',
    recordsPending: 'लंबित रिकॉर्ड',
    completedVisits: 'पूर्ण यात्राएं',
    targetPercent: '88% लक्ष्य',
    highRiskAlerts: 'उच्च जोखिम अलर्ट',
    urgent: 'तत्काल',
    reviewAvgTime: 'समीक्षा औसत समय',
    efficient: 'कुशल',

    // Patient Registry
    myPatientRecords: 'मेरे मरीज़ रिकॉर्ड',
    recordsFound: 'रिकॉर्ड मिले',
    searchByNameUhid: 'नाम, UHID, संपर्क से खोजें...',
    patient: 'मरीज़',
    dob: 'जन्म तिथि',
    facility: 'सुविधा',
    risk: 'जोखिम',
    updated: 'अपडेट',
    noRecords: 'कोई रिकॉर्ड नहीं मिला',
    noRecordsMatch: 'आपकी खोज से कोई रिकॉर्ड मेल नहीं खाता',
    filters: 'फ़िल्टर',
    status: 'स्थिति',
    all: 'सभी',

    // New Patient
    motherDetails: 'माता विवरण',
    enterMotherInfo: 'माता की व्यक्तिगत और संपर्क जानकारी दर्ज करें।',
    motherFullName: 'माता का पूरा नाम',
    fatherFullName: 'पिता का पूरा नाम',
    ageYears: 'आयु (वर्ष)',
    contactNumber: 'संपर्क नंबर',
    villageArea: 'गाँव / क्षेत्र',
    ashaWorkerName: 'ASHA कार्यकर्ता का नाम',
    ashaContact: 'ASHA संपर्क',
    babyDetails: 'शिशु विवरण',
    enterBabyInfo: 'नवजात शिशु की नैदानिक जानकारी दर्ज करें।',
    gender: 'लिंग',
    uhidLabel: 'UHID (अद्वितीय स्वास्थ्य आईडी)',
    areaType: 'क्षेत्र प्रकार',
    birthWeight: 'जन्म वज़न (किलो)',
    gestationalAge: 'गर्भावस्था आयु (सप्ताह)',
    breastfeedingCounselling: 'स्तनपान परामर्श',
    checkTopics: 'माता के साथ चर्चा किए गए सभी परामर्श विषयों की जांच करें।',
    colostrumFeeding: 'कोलोस्ट्रम फीडिंग',
    colostrumDesc: 'लाभ और पहले दूध के महत्व पर चर्चा की',
    earlyInitiation: 'प्रारंभिक प्रारंभ',
    earlyInitiationDesc: 'जन्म के पहले घंटे में स्तनपान',
    exclusiveBreastfeeding: 'एक्सक्लूसिव स्तनपान',
    exclusiveDesc: '6 महीने कोई अन्य भोजन नीति पर सलाह',
    correctLatching: 'सही लैचिंग',
    latchingDesc: 'पोज़िशनिंग और अटैचमेंट परामर्श किया गया',
    prelactealFeed: 'प्रीलैक्टियल फीड से बचा गया',
    prelactealDesc: 'प्रीलैक्टियल फीड से बचने के लिए परामर्श',
    additionalNotes: 'अतिरिक्त नोट्स',
    counsellingNotes: 'कोई विशिष्ट परामर्श नोट्स...',
    kmcTitle: 'KMC (कैंगरू मदर केयर)',
    kmcDesc: 'KMC प्रारंभ और परामर्श विवरण दर्ज करें।',
    kmcInitiated: 'KMC प्रारंभ किया',
    counsellingDone: 'परामर्श पूर्ण',
    providerSupport: 'प्रदाता सहायता आवश्यक',
    dateOfInitiation: 'प्रारंभ तिथि',
    durationHrsDay: 'अवधि (घंटे/दिन)',
    acceptanceLevel: 'स्वीकृति स्तर',
    selectLevel: 'स्तर चुनें',
    low: 'कम',
    moderate: 'मध्यम',
    high: 'उच्च',
    problemsEncountered: 'सामना आई समस्याएं',
    dischargeTitle: 'डिस्चार्ज और खतरे के संकेत',
    criticalModule: 'महत्वपूर्ण मॉड्यूल — माता के साथ सभी खतरे के संकेतों पर चर्चा करें',
    critical: 'महत्वपूर्ण',
    discussedDanger: 'चर्चा किए गए खतरे के संकेत',
    inabilityToFeed: 'फीड करने में अक्षमता',
    convulsions: 'दौरे / फिट',
    fastBreathing: 'तेज सांस (>60bpm)',
    fever: 'बुखार / ठंडा लगना',
    yellowingOfPalms: 'हथेलियों/तलवों का पीला होना',
    followupDate: 'फॉलो-अप तिथि',
    emergencyContact: 'आपातकालीन संपर्क पुष्टि?',
    yes: 'हां',
    no: 'नहीं',
    dischargeAdvice: 'डिस्चार्ज सलाह नोट्स',
    dischargeInstructions: 'माता के लिए विशिष्ट निर्देश दर्ज करें...',
    postDischarge: 'डिस्चार्ज के बाद फॉलो-अप',
    postDischargeDesc: 'डिस्चार्ज के बाद फॉलो-अप यात्रा विवरण दर्ज करें।',
    currentFeeding: 'वर्तमान फीडिंग स्थिति',
    selectStatus: 'स्थिति चुनें',
    satisfactory: 'संतोषजनक',
    partial: 'आंशिक',
    notBreastfeeding: 'स्तनपान नहीं कर रही',
    currentWeight: 'वर्तमान वज़न (किलो)',
    feedingPattern: 'फीडिंग पैटर्न',
    nextFollowup: 'अगली फॉलो-अप तिथि',
    kmcContinuedHome: 'KMC घर पर जारी',
    dangerSignsFound: 'खतरे के संकेत मिले',
    referral: 'रेफरल',
    remarks: 'टिप्पणियां',
    saveDraft: 'ड्राफ्ट सहेजें',
    saved: 'सहेजा गया!',
    submittedSuccess: 'मामला सफलतापूर्वक प्रस्तुत!',
    submittedSuccessDesc: 'रिकॉर्ड एडमिन समीक्षा के लिए प्रस्तुत किया गया है।',
    patientRegistration: 'मरीज़ पंजीकरण',
    stepOf: 'चरण {step} का {total}',
    discardEntry: 'प्रविष्टि हटाएं',
    previous: 'पिछला',
    nextSection: 'अगला अनुभाग',
    submitForReview: 'समीक्षा के लिए प्रस्तुत करें',

    // Settings
    managePreferences: 'अपनी खाता प्राथमिकताएं प्रबंधित करें',
    profile: 'प्रोफ़ाइल',
    security: 'सुरक्षा',
    fullName: 'पूरा नाम',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    updatePassword: 'पासवर्ड अपडेट करें',
    notificationsSettings: 'सूचनाएं',
    caseReturnedAlerts: 'मामला लौटाया अलर्ट',
    followupReminders: 'फॉलो-अप देय अनुस्मारक',
    adminRemarks: 'एडमिन टिप्पणियां',
    systemUpdates: 'सिस्टम अपडेट',

    // Reports
    reportsExports: 'रिपोर्ट और निर्यात',
    reportsDesc: 'PDF या Excel प्रारूप में रिपोर्ट बनाएं और डाउनलोड करें',
    monthlyReport: 'मासिक रिपोर्ट',
    monthlyReportDesc: 'एक विशिष्ट महीने के सभी पंजीकरण',
    supervisorReport: 'पर्यवेक्षक रिपोर्ट',
    supervisorReportDesc: 'पर्यवेक्षक द्वारा प्रदर्शन और कार्यभार',
    facilityReport: 'सुविधा रिपोर्ट',
    facilityReportDesc: 'सुविधा-वार मरीज़ आंकड़े',
    governmentReport: 'सरकारी रिपोर्ट',
    governmentReportDesc: 'स्वास्थ्य विभाग के लिए आधिकारिक प्रारूप',
    monthlySummaryPreview: 'मासिक सारांश पूर्वावलोकन',
    supervisorCaseload: 'पर्यवेक्षक कार्यभार',
    cases: 'मामले',

    // User Management
    userManagementTitle: 'उपयोगकर्ता प्रबंधन',
    activeSupervisors: 'सक्रिय पर्यवेक्षक',
    addSupervisor: 'पर्यवेक्षक जोड़ें',
    totalUsers: 'कुल उपयोगकर्ता',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    totalCases: 'कुल मामले',
    designation: 'पदनाम',
    joined: 'शामिल',

    // Facility
    facilityManagement: 'सुविधा प्रबंधन',
    facilitiesDesc: 'अस्पताल विभागों और इकाइयों का प्रबंधन करें',
    activeFacilities: 'सक्रिय सुविधाएं',
    addFacility: 'सुविधा जोड़ें',
    department: 'विभाग',
    head: 'प्रमुख',
    patients: 'मरीज़',

    // Other Supervisors Modal
    otherSupervisors: 'अन्य पर्यवेक्षक',
    allSupervisors: 'सभी पर्यवेक्षक',
    pending: 'लंबित',
    viewAllSupervisors: 'सभी पर्यवेक्षक देखें',
    close: 'बंद करें',

    // Assessment Tool - Section A
    identification: 'पहचान',
    hospitalName: 'अस्पताल का नाम',
    dateOfDelivery: 'प्रसव की तिथि',
    dateOfAssessment: 'मूल्यांकन की तिथि',
    assessorName: 'मूल्यांकनकर्ता का नाम',
    gravida: 'गर्भावस्था संख्या',
    para: 'प्रसव संख्या',
    sexOfBaby: 'शिशु का लिंग',
    deliveryType: 'प्रसव का प्रकार',
    normal: 'सामान्य',
    assisted: 'सहायता प्राप्त',
    caesarean: 'सिज़ेरियन',
    male: 'पुरुष',
    female: 'महिला',
    otherGender: 'अन्य',

    // Assessment Tool - Section B (ANC)
    ancCounselling: 'ANC परामर्श (प्रसव से पहले)',
    ancCounsellingDesc: 'क्या गर्भावस्था के दौरान माता को परामर्श दिया गया?',
    importanceBF: 'स्तनपान का महत्व',
    bfWithin1Hour: '1 घंटे के भीतर स्तनपान',
    exclusiveBF6Months: '6 महीने का एक्सक्लूसिव स्तनपान',
    skinToSkin: 'स्किन-टू-स्किन संपर्क',
    noPrelacteal: 'प्रीलैक्टियल फीड नहीं',
    breastAssessment: 'स्तन मूल्यांकन',
    flatNipple: 'सपाट निप्पल',
    invertedNipple: 'उल्टा निप्पल',
    breastAbnormality: 'स्तन विकृति',
    prevBFDifficulty: 'पिछला स्तनपान कठिनाई',
    actionTaken: 'की गई कार्रवाई',

    // Assessment Tool - Section C (After Birth)
    afterBirthCare: 'जन्म के तुरंत बाद देखभाल',
    afterBirthCareDesc: 'प्रसव कक्ष विवरण',
    timeOfBirth: 'जन्म का समय',
    babyCriedImmediately: 'शिशु ने तुरंत रोया',
    requiredResuscitation: 'पुनर्जीवन की आवश्यकता',
    driedImmediately: 'शिशु को तुरंत सुखाया',
    delayedCordClamping: 'विलंबित कॉर्ड क्लैम्पिंग',
    skinToSkinInitiated: 'स्किन-टू-स्किन संपर्क शुरू किया',
    durationOver1Hour: 'अवधि >1 घंटा',
    babySeparated: 'शिशु को माता से अलग किया',
    reason: 'कारण',
    timeBFStarted: 'स्तनपान शुरू का समय',
    withinOneHour: '1 घंटे के भीतर?',
    ifNoWhy: 'यदि नहीं, तो क्यों?',
    motherSick: 'माता बीमार',
    babySick: 'शिशु बीमार',
    staffDelay: 'स्टाफ विलंब',
    familyRefusal: 'परिवार से इनकार',
    colostrumGiven: 'कोलोस्ट्रम दिया?',
    prelactealGiven: 'प्रीलैक्टियल फीड दिया?',
    type: 'प्रकार',
    honey: 'शहद',
    water: 'पानी',
    formula: 'फॉर्मूला',
    animalMilk: 'पशु दूध',

    // Assessment Tool - Section D (Breastfeeding Assessment)
    bfAssessment: 'स्तनपान मूल्यांकन',
    bfAssessmentDesc: 'एक पूर्ण फीड देखें',
    position: 'स्थिति',
    correct: 'सही',
    incorrect: 'गलत',
    motherComfortable: 'माता सहज',
    babyCloseToMother: 'शिशु माता के पास',
    babyFacingBreast: 'शिशु स्तन की ओर',
    wholeBodySupported: 'पूरा शरीर सहारा',
    attachment: 'जुड़ाव',
    mouthWideOpen: 'मुंह चौड़ा खुला',
    chinTouchingBreast: 'ठोड़ी स्तन को छू रही',
    lowerLipOutward: 'निचला होंठ बाहर की ओर',
    moreAreolaAbove: 'अधिक एरिओला ऊपर दिखाई दे',
    effectiveSuckling: 'प्रभावी चूसना',
    slowDeepSuck: 'धीमी गहरी चूसन',
    swallowingHeard: 'निगलना सुना',
    babySatisfied: 'शिशु संतुष्ट',

    // Assessment Tool - Section E (Postnatal Ward)
    postnatalWard: 'प्रसवोत्तर वार्ड',
    bfObservedByNurse: 'क्या नर्स ने स्तनपान देखा?',
    everyFeed: 'हर फीड',
    onceDaily: 'दिन में एक बार',
    never: 'कभी नहीं',
    motherCounselled: 'माता को परामर्श दिया गया',
    feedingCues: 'फीडिंग संकेत',
    demandFeeding: 'मांग फीडिंग',
    nightFeeding: 'रात्रि फीडिंग',
    burping: 'डकार',
    handExpression: 'हाथ से दूध निकालना',
    familyCounselled: 'परिवार को परामर्श दिया?',

    // Assessment Tool - Section F (Sick Baby)
    sickBaby: 'बीमार शिशु के लिए (SNCU/NBSU)',
    applicable: 'लागू?',
    motherExpressingMilk: 'माता ने दूध निकालना शुरू किया',
    within6Hours: '6 घंटे के भीतर',
    within12Hours: '12 घंटे के भीतर',
    over12Hours: '>12 घंटे',
    feedingMethod: 'फीडिंग विधि',
    directBF: 'प्रत्यक्ष स्तनपान',
    cup: 'कप',
    spoon: 'चम्मच',
    tube: 'ट्यूब',
    expressedMilk: 'निकाला हुआ स्तन दूध',
    counselledDaily: 'माता को दैनिक परामर्श?',

    // Assessment Tool - Section G (Daily Monitoring)
    dailyMonitoring: 'दैनिक निगरानी',
    bfObserved: 'स्तनपान देखा गया',
    goodAttachment: 'अच्छा जुड़ाव',
    feeding8to12: 'शिशु 8–12 बार फीड',
    urinationAdequate: 'मूत्र पर्याप्त',
    stoolPassed: 'मल त्याग',
    weightMonitored: 'वज़न निगरानी',

    // Assessment Tool - Section H (Breastfeeding Problems)
    bfProblems: 'स्तनपान समस्याएं',
    poorAttachment: 'खराब जुड़ाव',
    breastEngorgement: 'स्तन में सूजन',
    crackedNipple: 'फटा निप्पल',
    inadequateMilk: 'अपर्याप्त दूध',
    babySleepy: 'शिशु नींद में',
    managementGiven: 'प्रबंधन दिया गया',

    // Assessment Tool - Section I (Before Discharge)
    beforeDischarge: 'डिस्चार्ज से पहले',
    exclusivelyBF: 'शिशु केवल स्तनपान?',
    motherConfident: 'माता आत्मविश्वासी?',
    exclusiveBFCounselling: 'एक्सक्लूसिव स्तनपान',
    dangerSignsCounselling: 'खतरे के संकेत',
    maternalNutrition: 'माता पोषण',
    homeVisitCounselling: 'घर यात्रा',
    immunization: 'टीकाकरण',
    followupCounselling: 'फॉलो-अप',

    // Assessment Tool - Section J (Post-discharge Plan)
    postDischargePlan: 'डिस्चार्ज के बाद योजना',
    ashaInformed: 'ASHA को सूचित?',
    hbncVisitPlanned: 'HBNC यात्रा योजना',
    day1: 'दिन 1',
    day3: 'दिन 3',
    day7: 'दिन 7',
    day14: 'दिन 14',
    day21: 'दिन 21',
    day28: 'दिन 28',

    // PatientDetailAdmin bilingual fixes
    admissionLevel: 'प्रवेश स्तर',
    permanentlyLocked: 'स्थायी रूप से लॉक',
    notYetFilled: 'अभी तक नहीं भरा',
    reviewSubmitted: 'समीक्षा प्रस्तुत!',
    caseStatusUpdated: 'मामले की स्थिति सफलतापूर्वक अपडेट की गई।',
    thisCaseLocked: 'यह मामला स्थायी रूप से लॉक है और इसे संशोधित नहीं किया जा सकता।',
    caseTimeline: 'मामला समयरेखा',
    adminReviewAction: 'एडमिन समीक्षा कार्रवाई',
    submitReview: 'समीक्षा प्रस्तुत करें',
    addReviewNotes: 'समीक्षा नोट्स या वापसी का कारण जोड़ें...',
    systemActivityLog: 'सिस्टम गतिविधि लॉग',
    recentEvents: 'हाल की घटनाएं',
    performedByLabel: 'द्वारा:',
    created: 'बनाया',
    motherName: 'माता का नाम',
    fatherName: 'पिता का नाम',
    age: 'आयु',
    contact: 'संपर्क',
    village: 'गाँव',
    ashaWorker: 'ASHA कार्यकर्ता',
    area: 'क्षेत्र',
    weeks: 'सप्ताह',
    years: 'वर्ष',
    kg: 'किलो',
    done: 'पूर्ण',
    notDone: 'नहीं किया',

    // Misc
    loading: 'लोड हो रहा है...',
    baby: 'का शिशु',
    of: 'का',
    babyOfName: '{name} का शिशु',

    // Mock Dashboard Follow-ups
    dateToday: 'आज, 16 अक्टूबर',
    dateTomorrow: 'कल, 17 अक्टूबर',
    babyOfAnanya: 'अनन्या का शिशु',
    babyOfPriya: 'प्रिया का शिशु',
    babyOfDeepa: 'दीपा का शिशु',
    followupDay14: 'फॉलो-अप: 14वें दिन की यात्रा',
    followupDay7: 'फॉलो-अप: 7वें दिन की यात्रा',
    routineWeightCheck: 'नियमित वज़न जांच',
    chcZone4: 'सामुदायिक स्वास्थ्य केंद्र – ज़ोन 4',
    homeVisitGreenPark: 'घर का दौरा – ग्रीन पार्क अपार्टमेंट्स',
    sncuOpd: 'एसएनसीयू ओपीडी',

    // Mock Names
    Meera: 'मीरा',
    Rekha: 'रेखा',
    Sunita: 'सुनीता',
    Meena: 'मीना',
    Priya: 'प्रिया',
    Sarah: 'सारा',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('sankalp_lang') || 'en';
    } catch {
      return 'en';
    }
  });

  const toggleLanguage = (newLang) => {
    setLang(newLang);
    try {
      localStorage.setItem('sankalp_lang', newLang);
    } catch {}
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
